### ISSUE TITLE
messy approach in coding, but good concept

### ISSUE THREAD

**Issue by ghost** [psineur/NSObject-AutomagicCoding#17]
messy approach in coding, but good concept

**Comment by ghost** [comment]
having any object carrying metadata that's maybe what people try to avoid, implementing a serializable interface is smarter

**Comment by psineur** [comment]
Ok, but this doesn't look like an issue.
Do you have any recommendations, patches or bugreports?

**Comment by ghost** [comment]
that's definitely a mind issue, see below for the recommendations, the caveat I am forced using a third party code which uses your bogus mind approach, I just hit the root of the disease, I have to deal with consequences just trying to heal the causes, to be blunt, the concept is good the implementation sucks deep. The only patch people could commit that's a complete reset.

I always steal Xmas candies from kids, I am bad.

**Comment by psineur** [comment]
Ok.
